spring:
  application:
    name: trend-trading-backtest-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hustrix:
    enabled: ture