spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          default-label: main
          uri: https://github.com/NewSelf1225/springcloudConfig.git
          search-paths:
            - respo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/